### ISSUE TITLE
Tabs go missing for the Android Manifest Editor

### ISSUE THREAD

**Issue by djehauti** [rogerdudler/eclipse-ui-themes#15]
Tabs go missing for the Android Manifest Editor, if I switch theme, restart eclipse they return, switch to 'Dark Juno' they still are there, but as soon as you click one, or restart eclipse again they will disappear.

**Comment by ghost** [comment]
Similar to #11

**Comment by djehauti** [comment]
Sorry for the dup, this is the exact same issue as #11, I'll close here, and watch there for updates

BTW of note the ALT-PgUp/PgDwn trick works for the Android Manifest Editor as well, and on the reclaimed real estate I'm going to put this in the feature bin as well now that I've got the keyboard shortcuts down.

**Comment by ghost** [comment]
@djehauti  :+1:
