### ISSUE TITLE
Don't working in Debian x64

### ISSUE THREAD

**Issue by dsalychev** [rogerdudler/eclipse-ui-themes#4]
## My environment:

<b>OS</b>: Debian 6.0.5 (Linux kernel 2.6.32-5-amd64), GNOME 2.30.2
<b>IDE</b>: Eclipse SDK (Eclipse Classic), Version: 4.2.0, Build id: I20120608-1400

I placed ZIP to <i>[eclipse_home]/dropins</i> and  extracted it here (now that look like <i>[eclipse_home]/dropins/plugins/com.github.eclipsecolortheme.themes_1.0.0.201207112226.jar</i>).

I can see theme's name in Preferences -> General -> Appearance, but nothing happened when I switched to it.

That's theme is so comfortable for me, thank for your work! If you need some more information - I am ready to give it.

**Comment by rogerdudler** [comment]
Can you try again with the fixed release - https://github.com/downloads/eclipse-color-theme/eclipse-ui-themes/com.github.eclipsecolortheme.themes_1.0.0.201207121019.zip

**Comment by dsalychev** [comment]
It's working! Thanks!
