### ISSUE TITLE
Multipage editor seem to be loosing its tabs

### ISSUE THREAD

**Issue by vogella** [rogerdudler/eclipse-ui-themes#8]
If I open a product definition file with the new theme the tabs for the multipage editor seem to go away. Some for MANIFEST.MF.

**Comment by vogella** [comment]
![Screenshot](http://snag.gy/w49hS.jpg)

**Comment by ghost** [comment]
@vogella You closed the issue. Did you find the solution?
Need help with Issue #11

**Comment by vogella** [comment]
I think it worked. If not please reopen it.

**Comment by ghost** [comment]
No. It hasn't been fixed yet.

**Comment by ghost** [comment]
I don't have enough privileges to reopen the issue.

**Comment by emilio-simoes** [comment]
I'm having this issue to both on Windows 7 x64 and Kubuntu 12.04 x64. This issues has not been fixed yet.
